### ISSUE TITLE
How to get instance track id for VOS?

### ISSUE THREAD

**Issue by Pilot-LH** [epic-kitchens/VISOR-VIS#2]
Thank you for sharing your great work! 
In a subsequence, how can I get the track id for each instance? I can only find instance id in each frame.

**Comment by dimadamen** [comment]
The unique entity name is how you would link instances to form tracks. There isn't a track-ID. The various instances in the sequence share the same entity name.
Hope this helps,

**Comment by Pilot-LH** [comment]
I see. 
<img width="1278" alt="Screen Shot 2022-08-24 at 4 23 13 PM" src="https://user-images.githubusercontent.com/32472261/186516218-44ba0306-d3e7-42df-b28d-e5e95da40f03.png">
So in this example, we don't know how to link two pans (pink) and two lids (blue) across frames, am I understanding right?

**Comment by dimadamen** [comment]
This is semantic segmentations, not instance segmentations... There is one "lid" entity made up of 2 polygons of the two lids. They are not separated into instances...
So you will have a "pan" track, tracking both pans, and a "lid" track, tracking both lids.

**Comment by Pilot-LH** [comment]
Got it. Thank you for the reply. Will close this issue.
